### ISSUE TITLE
C++ Engineering System for GA

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#157]
* [ ] Updated vcpkg script
* [ ] Code coverage (if applicable) 
* [ ] Publish test results
* [ ] Code coverage checks (consider existing coverage numbers)
* [ ] Ensure release artifact generation works in per-package model
* [ ] Live tests

**Comment by kurtzeborn** [comment]
Converting this to an Epic since there's a lot here.
