### ISSUE TITLE
HttpClient, azure::core::pipeline

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-cpp#16]
Design
- [x] Define HTTP Pipeline Design Pattern

Develop
- [x] Add HttpPolicy abstraction
- [x] Add Context
- [x] Add HttpPipeline abstraction
- [x] Add mechanism to replace the HttpPipeline
