### ISSUE TITLE
Infrastructure

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-cpp#2]
- [x] Create cmake build system
- [x] Initial check-in enabling first set of clang check styles rules
- [x] Setup initial CI system #31
- [x] Investigate unit test framework #21
