### ISSUE TITLE
[Documentation] Doxygen docs bash for Azure::Core

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2260]
- [x] Dropdown for docs is not listing all versions - #2270
- [x] The README at the root shows code sample/snippets with {C++} visible
       WIP Victor #2273
- [x] Drop distributed tracing from the root readme, and logging is already available, so update that - #2295
- [x] Add a section on how to turn on and customize logging - #2294
- [x] The root readme has important getting started info, where will that show up in the generated docs? - #2296
- [ ] Add BodyStream concept docs in the core readme - #2293
- [x] Within Azure Core, order the key concepts in order of importance and complexity, the end user doesn't need to know about http pipeline to start using the SDK, so go from most important to least. - #2295
- [x] Remove the `vcpkg publish automation assets` section from the concepts and related pages part of the docs.
- [x] Add periods at the end of all doc comments - [ ] doxygen seems to be removing it
      WIP - Victor - #2271
- [x] Add doc comments at the namespace level
- [x] Update doc wording of options to be more expressive and descriptive about what it's used for, what are valid/invalid, rather than just repeating the type name in doc comments. For example RetryOptions - #2297
- [ ] There is a "More..." link on certain docs that are meaningless and do nothing for small types/doxygen docs (like AccessToken) - #2272
- [x] AuthenticationException brief - [ ] missing `an` within the sentence
      WIP - Victor
- [ ] [low priority] Drop `Represents`, `Defines` and other "intro words" in the doc comment, and just state what it is.
- [x] Add commonly used template description for all simple/defaulted virtual dtors that give the reason for why we have it. - #2298
- [ ] Use words, by adding (s) like "Gets", "Returns", "Destroys", etc. and not "Get", "Return", "Destroy"
- [ ] Add `pre` tags for preconditions
- [x] Generated docs don't show some of the doc comments that are there in source, for example `Nullable::Value()` (possibly because it is a templated type)  - WIP - Victor
- [x] `operator #bool()` and `#GetValue()` are not getting linked/referenced correctly. Make sure API name is correct.
     WIP - Victor
- [ ] Add 2-5 liner code snippets for the most important or commonly used APIs, such as client ctors, that folks can use for getting started, maybe using `\example`
- [x] Have common phrasing as a starting point across all ctor/dtors for consistency. `Constructs the <type name>...`/`Destructs the <type name> ...` - #2298
- [ ] Avoid self-referential links on the same page
- [x] Add documentation for HttpMethod extensible enum
      WIP - Victor
- [x] Document delete functions like the default ctor, using a template statement. - #2298
- [x] Add docs to AZ_CORE_DLLEXPORT so the link show up.
- [x] Context Key has limited documentation and it needs to be improved
- [ ] Add docs to Tparam (for example Operation)
- [x] For bool returns, follow C, and do `; otherwise, false.` - #2298
- [ ] For multi-value returns, use `Return values`, similar to C
- [ ] Use `@note` to highlight important things to call out rather than `@remark`
- [x] HttpPolicy doc, add `@details`  - WIP - Victor
- [ ] DateTime ctor remark reword, change to: `This class can handle a DateTime...`
- [ ] Add example format for Rfc format enum in the docs.
- [ ] Link the actual RFC doc in docs.
- [ ] Figure out a good format for the generated docs for all the extensible enums.
- [ ] ETag docs have references that used to be in Azure::Core, make sure to reference the right namespace.
- [x] Can we add links to STL types, such as chrono millisecond.
- [x] Capitalize SSL.
- [x] Be consistent in docs on WinHttp vs WinHTTP (use [WinHTTP](https://docs.microsoft.com/en-us/windows/win32/winhttp/about-winhttp)) and CURL/Libcurl/curl/etc.

**Comment by ahsonkhan** [comment]
Unrelated to docs, @antkmsft remove Listener typedef and use function directly.

**Comment by ahsonkhan** [comment]
FYI @danieljurek - there might be a couple of things here that you might be able to help us on, for example the dropdown issue

**Comment by antkmsft** [comment]
I.e. #2270, #2271, #2272, #2273.

**Comment by antkmsft** [comment]
All the remaining work is extracted to individual items, which are planned for September-October (1 case):
* https://github.com/Azure/azure-sdk-for-cpp/issues/2293
* https://github.com/Azure/azure-sdk-for-cpp/issues/2299
* https://github.com/Azure/azure-sdk-for-cpp/issues/2300
* https://github.com/Azure/azure-sdk-for-cpp/issues/2304
* https://github.com/Azure/azure-sdk-for-cpp/issues/2732
* https://github.com/Azure/azure-sdk-for-cpp/issues/2367
