### ISSUE TITLE
Storage SDK Blob service feature parity

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2515]
until STG 74 (API version 2020-02-10)

- [x] xml tag `EnumerationResults.Where` and `EnumerationResults.Blobs.Blob.TagValue` in the response of `FindBlobsByTags` 
      `EnumerationResults.Where` is the same as query statement in request, there's no need to give the same value provided by the customer back to them. This aligns with the prefix parameter in list-blobs operations.
      `EnumerationResults.Blobs.Blob.TagValue` is going to be replaced with `Tags.TagSet` in STG75. We skipped this tag to avoid a breaking change.
- [x] Lease ID in `BlobContainerClient::GetAccessPolicy` request
- [x] xml tag `EnumerationResults.Blobs.BlobItems.Blob.Properties.{CopyId,CopyStatus,CopySource,CopyProgress,CopyCompletionTime,CopyStatusDescription,IncrementalCopy,DestinationSnapshot,DeletedTime,RemainingRetentionDays,ArchiveStatus,CustomerProvidedKeySha256,EncryptionScope,AccessTierChangeTime,TagCount,RehydratePriority}` and `EnumerationResults.Blobs.BlobItems.Blob.Tags.TagSet.Tag.{Key,Value}` in the response of `ListBlobs` and `ListBlobsByHierarchy`
- [x] `EnumerationResults.Blobs.BlobItems.Blob.Metadata.Encrypted`  in the response of `ListBlobs` and `ListBlobsByHierarchy`
       Metadata is encrypted with CPK, there's nothing we can do. .Net doesn't parse it either.
- [x] `x-ms-tags` header in `AppendBlobClient::Create` and `PageBlobClient::Create` and `BlockBlobClient::Upload` and `BlobClient::StartCopyFromUri` and `BlockBlobClient::CommitBlockList`
- [x] `ETag` and `Last-Modified` in `BlobClient::ScheduleDeletion`
- [x] `x-ms-request-server-encrypted`, `x-ms-encryption-key-sha256` and `x-ms-encryption-scope` aren't parsed in the response of `BlobClient::SetMetadata`.
- [x] `BlobClient::SetMetadata` doesn't return `x-ms-blob-sequence-number` at all. **This is a breaking change**.
        Won't fix
- [x]  `BlobClient::ReleaseLease` doesn't return `x-ms-blob-sequence-number` at all. 
- [x] `BlobClient::StartCopy` doesn't support `x-ms-source-lease-id` since 2012-02-12.
        Won't change.
- [x] `BlobClient::SetAccessTier` needs to support lease Id and if-tags
- [x] `PageBlobClient::UploadPagesFromUri` needs to support 4 source conditions.
- [x] Missing API: `PageBlobClient::UpdateSequenceNumber`
- [ ] Blob Batch
- [ ] Query
- [ ] Change Feed

**Comment by Jinming-Hu** [comment]
partial done in https://github.com/Azure/azure-sdk-for-cpp/issues/2515

**Comment by kshcherbatov** [comment]
Looking forward for BlobBatch!
Is there a way to schedule several deletions at a time without it?..

**Comment by kshcherbatov** [comment]
Were there known problems with BlobBatch implementation removed with 4527798bd1fc0cf0687fe35eda912b9d458b61a6 for #1309?
As a temporary workaround, I would love to revert it...

**Comment by Jinming-Hu** [comment]
> Is there a way to schedule several deletions at a time without it?..

No.

> Were there known problems with BlobBatch implementation removed with 4527798 for #1309?

The API interface wasn't approved by arch board. We're going to redesign the API interface.

**Comment by Jinming-Hu** [comment]
close in favor of https://github.com/Azure/azure-sdk-for-cpp/issues/3566
