### ISSUE TITLE
Azure.Core

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-cpp#3]
**Azure.Core**
- [x] Define exchange data types
- [x] Define HTTP Request Builder (URL, Path, Query Parameters, Headers, Body) #25 (victor)
- [x] Define HTTP Response Parser (Headers, Body) #26 
- [x] Define HTTP Pipeline Design Pattern #16 (gilbertw)
- [ ] Define HTTP Pipeline Policies
    - [x] Retry #17 (Anton)
    - [x] Authentication #18 (Anton)
    - [x] Logging #19
    - [x] Request ID #20
- [x] Define level of customer configuration of Policies
