### ISSUE TITLE
Storage SDK service feature parity

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#3566]
Blobs:

- STG81 (2021-04-10)

  - [ ] Identity-based Import-Export for Managed Disks

- STG78 (2020-10-02)

  - [x] OAuth support for sync copy ({Copy,StageBlock,AppendBlock,UploadPages}FromUri)

- STG 76 (2020-06-12)

  - [x] Batch scoping subrequests to specific container

- before STG 74 (2020-02-10)

  - [x] Blob Batch
  - [ ] Change Feed
  - [x] Bearer Challenge

Files Shares:

- STG82 (2021-06-08)

  - [x] Rename File x-ms-content-type Support
  - [x] Converting SMB-specific timestamps and headers to optional in Create/Set File/Directory APIs
  - [x] Files Service OAuth Support

- STG78 (2020-10-02)

  - [x] OAuth support for sync copy ({Copy,StageBlock,AppendBlock,UploadPages}FromUri)

**Comment by Jinming-Hu** [comment]
Ohers are not planned for now.
