### ISSUE TITLE
Storage test enhancement

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#3592]
Common:

- [x] Add some basic tests for the simplified storage header that customers use as a sanity check. https://github.com/Azure/azure-sdk-for-cpp/issues/976 https://github.com/Azure/azure-sdk-for-cpp/pull/4880
- [x] Enable tests after storage server fixes the issue where sas access policy isn't effective after 30 seconds https://github.com/Azure/azure-sdk-for-cpp/issues/1113
- [ ] Find a better way to wait until config comes into effect rather than just sleep https://github.com/Azure/azure-sdk-for-cpp/issues/1115

Blobs:
- [ ] Add connection reuse test for 40x request when libcurl transport supports connection reuse in case of 40x request.
- [x] Enable test case HighThroughputAppendBlob when ready to set features to on.https://github.com/Azure/azure-sdk-for-cpp/pull/4586 https://github.com/Azure/azure-sdk-for-cpp/pull/4806
- [x] Enable test case LastAccessTime when ready to set LAT features to on. https://github.com/Azure/azure-sdk-for-cpp/pull/4856
- [x] Enable test case SetColdTier when ready to set cold tier feature to on. https://github.com/Azure/azure-sdk-for-cpp/pull/4121 https://github.com/Azure/azure-sdk-for-cpp/pull/4819
- [x] Enable encryption scope test case by setting the encryption scope with post deployment script. https://github.com/Azure/azure-sdk-for-cpp/issues/862
- [x] Enable Arrow when it's available everywhere. https://github.com/Azure/azure-sdk-for-cpp/pull/3960

DataLake:

- [x] `Move` permission doesn't work in DataLake Sas (works in euap) https://github.com/Azure/azure-sdk-for-cpp/issues/660
- [ ] Add test case for add permission in DataLake Sas when AppendBlob is supported in HNS account https://github.com/Azure/azure-sdk-for-cpp/issues/659
- [x] Enable ListSystemFileSystems. Now the test account on the pipeline does not have system type fileSystems. https://github.com/Azure/azure-sdk-for-cpp/pull/3929
- [x] Enable ListDeletedPaths and UndeletePath. Now the datalake test account on the pipeline can't open soft delete feature. https://github.com/Azure/azure-sdk-for-cpp/pull/3963

File Share:

- [ ] Jumbo File testing https://github.com/Azure/azure-sdk-for-cpp/issues/472
