### ISSUE TITLE
Storage DataMovement Library

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#3603]
- [ ] Blob Virtual Directory
- [ ] Scheduler
  - [ ] Job Basics
  - [ ] Thread Pool
- [ ] Single Upload Job
- [ ] Single Download Job
- [ ] Directory Upload Job
- [ ] Directory Download Job
- [ ] Job Pause & Resume
  - [ ] Journal file
- [ ] Job Cancellation

**Comment by Jinming-Hu** [comment]
related PR https://github.com/Azure/azure-sdk-for-cpp/pull/3618 https://github.com/Azure/azure-sdk-for-cpp/pull/3594
