### ISSUE TITLE
Azure.Identity

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-cpp#5]
Create the identity library 

azure::identity
- [ ] Determine how we will incorporate MSAL
- [ ] Define AuthenticationClient abstract class
- [ ] Define types of authentication that are in scope, initially
    - [ ] client secret credential
    - [ ] client certificate credential
    - [ ] environment credential
    - [ ] managed identity credential
    - [ ] default azure credential

- [ ] Implement proposed API including underlying private classes
- [ ] Create unit and integration tests

**Comment by antkmsft** [comment]
Scott's suggestion is to implement the same as Go did.
Ge suggests the following:
* client secret credential
* client certificate credential
* environment credential
* managed identity credential
* default azure credential

Client certificate credential will require some SSL library dependency, most likely we will take OpenSSL.

Two most expensive credential types to implement are Client Certificate and Managed Identity.

Scott thinks it will take 8 weeks total to implement these, Managed Identity taking 3 weeks out of 8.

**Comment by antkmsft** [comment]
Let's also check with Speech and Storage which credentials they need, during our Friday sync.

**Comment by gilbertw** [comment]
@antkmsft Can you open an Issue for each credential and attach to this Epic.

**Comment by RickWinter** [comment]
@antkmsft Consolidate this Epic with the December Identity epic and then close this epic

**Comment by chuyiwtree** [comment]
Thank you @Jinming-Hu 

Hello,

We have an application which runs on azure VM and uses azure C++ storage sdk to interact with blob storage. We need to authenticate this application to have blob storage access. Currently we do it by passing storage account and account key as input from the user and create a storage client. However since we are running on azure VM, we want to avoid getting credentials from user.
 
Does the azure C++ storage sdk(Or identity Library) support reading required credentials from VM or getting managed identities?  Basically is there any functionality similar to instance profiles in AWS/Default service account in GCP for azure C++ sdk(Azure identity Library)?

Thanks a lot!
