### ISSUE TITLE
Add ContinuousAccessEvaluation

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#5934]
Add CAE support in C++.

```[tasklist]
### Tasks
- [ ] Modify BearerToken policy to handle CAE
- [ ] Add options for token requests
- [ ] Update credentials to do the right thing with options
- [ ] Add protocol for token requests
- [ ] Seperate token caches to not cache CAE with non-CAE
```

```[tasklist]
### Tasks
- [ ] Add Client to test feature, ARM?
```

**Comment by ahsonkhan** [comment]
This feature is blocked on MSAL support for CAE in C++
