### ISSUE TITLE
KeyVault::Keys library

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#857]
Add support for KeyVault::Keys
- [x] Create KeyVault Package
- [x] KeyVault common functionality
- [x] Keys api's
  - [x] Issues created to track each issue
- [x] API review with API board
- [x] Live Tests
- [x] Unit Tests
- [x] Documentation
- [x] Samples

**Comment by jefft0** [comment]
This task was closed. Is it completed, or is there a follow-up task?
